name: Lint and Format Check
on:
  pull_request:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run lint check and format check
        run: pnpm check