name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm 📦
        with:
          version: 11
          run_install: false

      - name: Install Node.js 🌐
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies 📦
        run: pnpm install

      - name: Run lint check and format check ✅
        run: pnpm check

      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
